### ISSUE TITLE
Suggestion: Add additional switches

### ISSUE THREAD

**Issue by tk101-fs** [crowbait/robocopy-gui#1]
One example: the settings window could show a toggle for the /sl switch, which will control whether robocopy follows the symlink and copies the files at that linked location, or instead just copies the symlink itself.

**Comment by crowbait** [comment]
That is a very good suggestion, which I will implement.
I have implemented the switches I use in may day-to-day business, so I'm not entirely certain which flags would be useful to other users. I don't want to indiscriminately implement every option, because they are just too many and most of them are not really useful in most cases.
As you said "one example", I take it there are more switches you'd like implemented? If so, please just list them here and I'll get to it in the next update.

**Comment by crowbait** [comment]
I deliberately let this float around to give enough time for additional suggestions to pile up; if any.
I will now close this thread, so that if anyone wants or needs additional switches, a new Issue must be opened. I don't want this thread to be cluttered.
